### ISSUE TITLE
Possible issues with deduction guides from p1518r2

### ISSUE THREAD

**Issue by jbcoe** [jbcoe/value_types#501]
Does https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1518r2.html somehow also apply to indirect?

I.e. should it be:

```diff
- constexpr indirect(allocator_arg_t, const Allocator& a, const indirect& other);
+ constexpr indirect(allocator_arg_t, const type_identity_t<Allocator>& a, const indirect& other);

- constexpr indirect(allocator_arg_t, const Allocator& a, indirect&& other);
+ constexpr indirect(allocator_arg_t, const type_identity_t<Allocator>& a, indirect&& other);
```

I am not sure, but I got reminded of P1518 and at least wanted to mention it.

Possibly related: https://github.com/microsoft/STL/issues/4060

We're currently consistent with tuple: https://eel.is/c++draft/tuple.tuple which might be the right way to be.

Taken from conversation with @Ukilele on another issue #497

**Comment by Ukilele** [comment]
There is a difference between `std::tuple` and `std::indirect`:
For `std::tuple`, the template parameter `Alloc` is a parameter of the constructor. For `std::indirect`, the template parameter `Allocator` is a parameter of the class. For `std::tuple` the templat parameter `Alloc` must be deduced from an argument that a user passes to the constructor call. But for `std::indirect` the `Allocator` type can/will be deduced from the `const indirect& other` (the last parameter of the constructor of `std::indirect`).

So the scenario would be the following, taken from [p1518](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1518r2.html):

https://value_type.compiler-explorer.com/z/cPWzTGb87
```c++
using xyz::indirect;
using PA = std::pmr::polymorphic_allocator<int>;

int main()
{
    std::pmr::monotonic_buffer_resource mr;
    std::pmr::polymorphic_allocator<int> a = &mr;
    indirect<int, PA> pi(std::allocator_arg, a);

    auto i1 = indirect<int, PA>(pi);
    auto i2 = indirect<int, PA>(std::allocator_arg, a, pi);
    auto i3 = indirect<int, PA>(std::allocator_arg, &mr, pi);

    auto di1 = indirect(pi);
    auto di2 = indirect(std::allocator_arg, a, pi);
    auto di3 = indirect(std::allocator_arg, &mr, pi); //Error here
}
```

The line `auto di3 = indirect(std::allocator_arg, &mr, pi)` fails with an error about failing class template argument deduction.
And I think we would want that line to work and compile and deduce `di3` to be `indirect<int, PA>`. Hence, I tend to think that we would want to adopt the changes from P1518. and apply the diff using `type_identity_t`.

**Comment by Quuxplusone** [comment]
(Author of P1518 here.) Yep, I agree with @Ukilele's latest comment:
```
    auto pi = indirect<int, PA>();
    auto di1 = indirect(pi);  // OK
    auto di2 = indirect(std::allocator_arg, a, pi);  // OK
    auto di3 = indirect(std::allocator_arg, &mr, pi);  // error, but should be OK
```
So basically P3019r11's signatures
```
constexpr indirect(const indirect& other);
constexpr indirect(allocator_arg_t, const Allocator& a, const indirect& other);
constexpr indirect(indirect&& other) noexcept;
constexpr indirect(allocator_arg_t, const Allocator& a, indirect&& other) noexcept(see below);
```
should be amended to
```
constexpr indirect(const indirect& other);
constexpr indirect(allocator_arg_t, const type_identity_t<Allocator>& a, const indirect& other);
constexpr indirect(indirect&& other) noexcept;
constexpr indirect(allocator_arg_t, const type_identity_t<Allocator>& a, indirect&& other) noexcept(see below);
```
and likewise for `polymorphic`.

N.B.: All the other constructors, e.g.
```
template <class U=T>
 explicit constexpr indirect(allocator_arg_t, const Allocator& a, U&& u);
```
should stay as they are (unless I'm brain-farting here). For example, the ctor above will be used for `indirect(allocator_arg, pa, 42)`, which will deduce `U=int` but be unable to deduce `T`, so CTAD will fail — we never get around to caring what `Allocator` might be deduced as. ...Well, actually, you have a deduction guide for that: `indirect(allocator_arg, pa, 42)` will use the deduction guide and deduce `indirect<int, decltype(pa)>`. Even so, we can't handle `indirect(allocator_arg, &mr, 42)` in any event. (Because `&mr` is of type `memory_resource*`, which is not an allocator type, and there are an infinity of candidate allocator types it _might_ enjoy converting to. Without an existing `indirect<T,Allocator>` object in the argument list, we can't guess what `Allocator` ought to be.)

**Comment by jbcoe** [comment]
Thanks @Quuxplusone @Ukilele 

This looks like an unambiguous problem with a clear solution. 

Can this solution be applied later without it being a breaking change? If not I’ll need to contact LWG and LEWG to broaden the scope of our discussion for Hagenburg and update our draft. If the fix can be applied later, perhaps the two of you would like to write a short paper and present it? I don’t want to deny others the opportunity to share their work and take credit.

**Comment by Ukilele** [comment]
Regarding Arthur's comment:
> and likewise for polymorphic.

Yes, indeed for `polymorphic` a similar change should be applied to these two constructors:
```c++
constexpr polymorphic(allocator_arg_t, const Allocator& a, const polymorphic& other);
constexpr polymorphic(allocator_arg_t, const Allocator& a, polymorphic&& other) noexcept(see below);
```

Answering your comment, Jon:
> Can this solution be applied later without it being a breaking change?

Yes. Similarly as [p1518](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1518r2.html) was retrospectively applied to all the containers in the STL. All it does is: Make CTAD, which does not compile today, compile.

I don't think it's an important feature and would prefer to see `indirect` & `polymorphic` rather sooner without this specific CTAD than later. I don't mind if anybody else writes the paper. Otherwise, I would pick it up (alone or in a joint effort). I will not make it to any of the ISO meetings in 2025 so the time frame would be slightly unclear.

**Comment by Quuxplusone** [comment]
I've emailed the LWG reflector just now. My experience in LWG leads me to believe that all you have to do is issue a P3019R13 with this tiny patch; I don't think that will cause it to miss plenary even in Hagenberg, let alone miss the C++26 train. All you have to do is say "oops, yeah, consistency with CTAD was my _intent_, here's the two-line patch" and you'll be fine.

(Preferably, say it by replying in that LWG reflector thread.)

**Comment by jbcoe** [comment]
While we can hold off changes to the draft while we wait for a reply from the relevant C++ Standards Committee folk, is anyone inclined to make additions/changes to the reference implementation and tests? We can hide them behind a macro if needed.

**Comment by Ukilele** [comment]
I've implemented it for `indirect` and _think_, I did it right: https://github.com/Ukilele/value_types/commit/4b6111246031477cd69072f9b053df2bdf04f462

Good that you found: https://github.com/llvm/llvm-project/issues/57646. I circumvented the issue by using `std::enable_if` [here](https://github.com/Ukilele/value_types/commit/4b6111246031477cd69072f9b053df2bdf04f462#diff-01332f5efea881b38f49805d6919e3525724aaadaf53ba1a3cb056d24850aae1R439).

I guess one outcome/finding of this is, that we have to constraint this deduction guide
```c++
template <class Allocator, class Value>
indirect(allocator_arg_t, Allocator, Value) -> indirect<Value,
         typename allocator_traits<Allocator>::template rebind_alloc<Value>>;
```
in such a way, that it only participates in overload resolution if `Value` is not `xyz::indirect`. Otherwise, the line:
```c++
  xyz::indirect copyDestination(std::allocator_arg, &mr, input_indirect);
```
would favor that explicit deduction guide and fail at `allocator_traits<Allocator>`, because `Allocator` would be e.g. `std::pmr::memory_resource*` (or `std::nullptr_t` as in my unit test [here](https://github.com/Ukilele/value_types/commit/4b6111246031477cd69072f9b053df2bdf04f462#diff-71145326fd4b7f894ff698af1e91361f5e290ed0c428ed937900370d0b06609eR143));

Note that I have issues with `polymorphic`, WIP.

**Comment by Quuxplusone** [comment]
@Ukilele: Hm, I had not considered that aspect. I see now that `indirect` isn't so much like `vector` or `queue` as it is like `reverse_iterator` or `optional` — it's simply 100% unsafe to use any of its constructors with CTAD. (See my previous writings such as [1](https://quuxplusone.github.io/blog/2018/12/09/wctad/), [2](https://quuxplusone.github.io/blog/2022/08/02/reverse-iterator-ctad/).) So while I still think it's appropriate to add the `type_identity_t`s as we established originally — because that's consistent with the rest of the STL — I'm suddenly much less interested in trying to make CTAD "work" for `indirect` and would even be well-disposed toward a proposal that tried to "disable" CTAD for `indirect` (except that such a proposal would require some _very_ novel technique and thus be inappropriate for P3019).

https://value_type.compiler-explorer.com/z/jYYreqnPh
```
    auto i = 42;
    auto j = indirect(42);
    auto k = indirect<int, A<int>>(42);

    std::same_as<indirect<int, A<int>>>
    auto di = indirect(std::allocator_arg, a, i);

    std::same_as<indirect<indirect<int>, A<indirect<int>>>> 
    auto dj = indirect(std::allocator_arg, a, j);

    std::same_as<indirect<int, A<int>>> 
    auto dk = indirect(std::allocator_arg, a, k);
```

**Comment by jbcoe** [comment]
Thanks @Quuxplusone . I’m not sure that I see why deduction guides for indirect are ‘unsafe’. 

Could you give an explicit example? I can’t quite piece together the problem from your references and it would be good to get all the necessary information here in one place.

**Comment by Quuxplusone** [comment]
> Could you give an explicit example?

I don't have any "[from the Book](https://en.wikipedia.org/wiki/Proofs_from_THE_BOOK)" example (like I do for `reverse_iterator`), because I haven't looked hard at `indirect` or how we expect it to be used in real life. But a really simple _toy_ example is, like,
https://godbolt.org/z/cqsaTo9j3
```
template<class T>
void mything(T t) {
  auto copy = xyz::indirect(t); // 0
  assert(*copy == t); // 1
  assert(sizeof(*copy) == sizeof(t)); // 2
}

int main() {
    mything(42);  // 1 OK, 2 OK
    mything(xyz::indirect<int>());  // 1 OK, 2 boom!
}
```
The issue here is "obvious"; but since it bites only for certain template-type-inputs and since the point of error (line 2) is separated visually from the point of the bug (the CTAD use on line 0), I consider that the best guideline is never to write something like line 0 at all.

**Comment by jbcoe** [comment]
Thanks @Quuxplusone. I’m afraid it’s still not quite obvious to me. 

Are we any worse than optional?

Would you recommend removing CTAD and adding ‘make_indirect’?

**Comment by Quuxplusone** [comment]
> Are we any worse than optional?

No, `indirect` is roughly the same as `optional`. The big difference is that `optional` doesn't have to care about allocators (which is how we ended up talking about CTAD here at all). But `tuple` _does_ have to care about allocators, so `indirect` is sitting somewhere between `optional` and `tuple` — still _basically_ in the realm of prior art with which we can afford to be consistent.

> Would you recommend removing CTAD

No, because that would be novel and tricky. As I said [above](https://github.com/jbcoe/value_types/issues/501#issuecomment-2599849117), though, I think it's no longer achievable to make CTAD "100% work" for `indirect`, so I discourage any _heroic_ attempts to make it work better than it already does. (IMHO adding `type_identity_t` in these two places is not heroics, it's just consistency. Adding _`is-indirect`_ constraints _might_ count as heroics; but you do already have that exposition-only concept sitting around for other reasons, so I guess you might as well use it as @Ukilele suggests. I defer to him on that.)

...Actually, @Ukilele, did you see [what `tuple` does](https://eel.is/c++draft/tuple#tuple) in its similar situation? It doesn't constrain a deduction guide on `not is-tuple-v<U>`; instead, it provides a second "more specialized" deduction guide.

```
  template<class... UTypes>
    tuple(UTypes...) -> tuple<UTypes...>;
  template<class Alloc, class... UTypes>
    tuple(allocator_arg_t, Alloc, UTypes...) -> tuple<UTypes...>;
  template<class Alloc, class... UTypes>
    tuple(allocator_arg_t, Alloc, tuple<UTypes...>) -> tuple<UTypes...>;
```
So for `indirect`, it _might_ look like this:
```
  template<class Value>
    indirect(Value) -> indirect<Value>;
  template<class Value, class Alloc>
    indirect(allocator_arg_t, Alloc, Value) -> indirect<Value, typename allocator_traits<Alloc>::template rebind_alloc<Value>>;
  template<class Value, class Alloc, class UAlloc>
    indirect(allocator_arg_t, UAlloc, indirect<Value, Alloc>) -> indirect<Value, Alloc>;
```
_If_ that does at least as well on all of @Ukilele's tests as any other alternative, then I would recommend it because it seems simple and relatively consistent with `tuple`.

> and adding `make_indirect`?

Well, yes, it'd certainly be _nice_ and _consistent_ to provide a factory function just like `make_pair` and `make_optional` and so on, so personally I'd recommend doing so. But my understanding is that the proposal has already gotten all the way through LEWG and LWG without anyone _else_ caring about the lack of `make_indirect`. So I'd say "it is what it is" in that area at this point.

**Comment by Ukilele** [comment]
I am sorry that I turned so silent in this issue. I thought about the use case of CTAD with `indirect` as well as the use case of CTAD with `polymorphic`.

I didn't come to a conclusion for `polymorphic` yet. 

Regarding `indirect`, there are two scenarios where I have used a type like `indirect`. The first is to implement the Pimpl idiom. The second is to achieve something like boost::recursive_variant for the sake of building up an expression-tree. Something like:
```c++
struct binary_op;
using expression = std::variant<int, binary_op>;
struct binary_op {
    char op;
    xyz::indirect<expression> lhs;
    xyz::indirect<expression> rhs;
};
```
Never would my code have gained any advantage by using CTAD. Because most (all?) of the time, declarations of `xyz::indirect` occur within the scope of a class as a data member. And CTAD isn't allowed/possible there anyway.

I would be curious to hear if you have other experiences with the usage of `indirect` which would benefit from CTAD.

**Comment by jbcoe** [comment]
We won't get time to present ideas on deduction guides at the Hagenberg ISO C++ meeting (9-16 Feb) with any certainty. I'm going to leave these proposed improvements to be addressed in a follow up paper, as a defect or as a National Body comment.

I'd encourage @Ukilele and @Quuxplusone to look into authoring such a paper. I'm happy to support this in any way I can.

**Comment by jbcoe** [comment]
Code changes are (i believe) made here: https://github.com/jbcoe/value_types/pull/556
